apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-argo
  namespace: argocd
spec:
  project: default
  source:
    path: influxdb
    repoURL: https://github.com/joseeetm/argo-kustomize
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: influx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
