apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    spec:
      containers:
        - name: influxdb
          env:
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "true"
            - name: INFLUXDB_REPORTING_DISABLED
              value: "true"
            - name: INFLUXDB_BIND_ADDRESS
              value: "0.0.0.0:8088"
            - name: "INFLUXDB_META_LOGGING_ENABLED"
              value: "true"
            - name: "INFLUXDB_DATA_INDEX_VERSION"
              value: "tsi1"
            - name: "INFLUXDB_DATA_QUERY_LOG_ENABLED"
              value: "true"
            - name: "INFLUXDB_HTTP_FLUX_ENABLED"
              value: "true"
            - name: "INFLUXDB_HTTP_LOG_ENABLED"
              value: "true"
            - name: "INFLUXDB_LOGGING_SUPPRESS_LOGO"
              value: "true"
            - name: INFLUXDB_ADMIN_USER
              value: "iometrics"
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-admin-credentials
                  key: password
