apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  ports:
  - name: http
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: rpc
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: influxdb
